
services:
  # Cassandra instance
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cassandra-metrics-demo
    # environment:
    #   - JMX_PORT=7199
    #   - LOCAL_JMX=no
    #   - JVM_OPTS=-Dcom.sun.management.jmxremote.rmi.port=7199 -Djava.rmi.server.hostname=cassandra
    ports:
      - "9042:9042"
      - "7199:7199"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  # Load generator to continuously create traffic
  load-generator:
    build:
      context: ./load-generator
    container_name: cassandra-load-generator
    depends_on:
      cassandra:
        condition: service_healthy
    restart: always
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - OPERATIONS_PER_SECOND=100
