FROM httpd:latest
COPY ./src/index.html /usr/local/apache2/htdocs/
COPY ./src/style.css /usr/local/apache2/htdocs/
COPY ./src/script.js /usr/local/apache2/htdocs/
COPY ./src/assets /usr/local/apache2/htdocs/assets
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
